In [6]:
#------- EXERCICI 1 --- ACABAT
from sklearn.datasets import load_iris

iris = load_iris()

dimensiones_especie = iris.data 
clase_especie = iris.target

print(dimensiones_especie[:10])

print(clase_especie[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]


In [7]:
#------- EXERCICI 2 --- ACABAT
import numpy as np

dimensiones_clase_especie = np.column_stack((dimensiones_especie, clase_especie))

print(dimensiones_clase_especie[:5])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [8]:
## ------- EXERCICI 3 --- ACABAT    

print('La mediana de la longitud del sépalo es de', round(np.mean(dimensiones_especie[:,0]), 2), 'cm')
print('La desviación estandar de la longitud del sépalo es de', round(np.std(dimensiones_especie[:,0]), 2), 'cm')
print('La mediana de la longitud del pétalo es de', round(np.mean(dimensiones_especie[:,2]), 2), 'cm')
print('La desviación estandar de la longitud del pétalo es de', round(np.std(dimensiones_especie[:,2]), 2), 'cm')

La mediana de la longitud del sépalo es de 5.84 cm
La desviación estandar de la longitud del sépalo es de 0.83 cm
La mediana de la longitud del pétalo es de 3.76 cm
La desviación estandar de la longitud del pétalo es de 1.76 cm


In [9]:
#------- EXERCICI 4 --- ACABAT
from numpy import random

print(dimensiones_clase_especie[np.random.choice(len(dimensiones_clase_especie), 20)])

[[5.6 2.9 3.6 1.3 1. ]
 [6.5 3.  5.8 2.2 2. ]
 [6.3 2.7 4.9 1.8 2. ]
 [6.3 2.5 4.9 1.5 1. ]
 [6.1 3.  4.6 1.4 1. ]
 [5.1 3.5 1.4 0.2 0. ]
 [6.2 3.4 5.4 2.3 2. ]
 [5.8 2.6 4.  1.2 1. ]
 [5.8 4.  1.2 0.2 0. ]
 [6.3 2.9 5.6 1.8 2. ]
 [6.  3.  4.8 1.8 2. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.  2.  3.5 1.  1. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.4 3.  4.5 1.5 1. ]
 [5.8 2.7 5.1 1.9 2. ]
 [5.6 3.  4.1 1.3 1. ]
 [5.5 3.5 1.3 0.2 0. ]
 [6.1 2.8 4.7 1.2 1. ]
 [5.  3.4 1.5 0.2 0. ]]


In [10]:
#------- EXERCICI 5 --- ACABAT

filtro_por_especie = np.unique(dimensiones_clase_especie[:, 4])

mean = []
std = []

for especie in filtro_por_especie:
    etiqueta_especie = dimensiones_clase_especie[dimensiones_clase_especie[:, 4] == especie]
    mean_dimensiones_especie = np.round(np.mean(etiqueta_especie, axis=0), 2)
    std_dimensiones_especie = np.round(np.std(etiqueta_especie, axis=0), 2)
    mean.append(mean_dimensiones_especie)
    std.append(std_dimensiones_especie)  
    
arr_mean = np.array(mean)                
arr_std = np.array(std)

print([arr_mean, arr_std])

[array([[5.01, 3.43, 1.46, 0.25, 0.  ],
       [5.94, 2.77, 4.26, 1.33, 1.  ],
       [6.59, 2.97, 5.55, 2.03, 2.  ]]), array([[0.35, 0.38, 0.17, 0.1 , 0.  ],
       [0.51, 0.31, 0.47, 0.2 , 0.  ],
       [0.63, 0.32, 0.55, 0.27, 0.  ]])]


In [11]:
#------- EXERCICI 6 --- ACABAT

nombres_clase_especie = iris.target_names

print('Las cantidades de las especies setosa, versicolor y virginica son respectivamente de:')

for cantidad in np.unique(clase_especie):
    cantidad_registros_especie = clase_especie[cantidad == clase_especie]
    print(np.shape(cantidad_registros_especie))  
    
especie_max_mean_long_sepalo = nombres_clase_especie[arr_mean[:, 0] == np.max(arr_mean)] 
print('La especie con el valor máximo de mediana de la variable "longitud del sépalo" es:', especie_max_mean_long_sepalo)

Las cantidades de las especies setosa, versicolor y virginica son respectivamente de:
(50,)
(50,)
(50,)
La especie con el valor máximo de mediana de la variable "longitud del sépalo" es: ['virginica']


In [12]:
#------- EXERCICI 7 --- ACABAT

print('La matriz de correlación entre las variables es de:')
print(np.corrcoef(dimensiones_especie, rowvar=False))

registros_sup_max_mean_long_petalo = dimensiones_especie[dimensiones_especie[:, 2] > np.mean(dimensiones_clase_especie[:, 2])]
print('Los valores superiores a la mediana de longitud de los pétalos son:')
print(registros_sup_max_mean_long_petalo[:, 2])

filtro_max_long_petalo = np.max(dimensiones_clase_especie[:,2])
print('La muestra con los pétalos más grandes es:', dimensiones_clase_especie[dimensiones_clase_especie[: , 2] == filtro_max_long_petalo])

La matriz de correlación entre las variables es de:
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
Los valores superiores a la mediana de longitud de los pétalos son:
[4.7 4.5 4.9 4.  4.6 4.5 4.7 4.6 3.9 4.2 4.  4.7 4.4 4.5 4.1 4.5 3.9 4.8
 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.8 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.  4.4
 4.6 4.  4.2 4.2 4.2 4.3 4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1 5.1
 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.  4.8 4.9 5.6
 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9 5.7 5.2 5.
 5.2 5.4 5.1]
La muestra con los pétalos más grandes es: [[7.7 2.6 6.9 2.3 2. ]]


In [ ]:
#------- EXERCICI 8 --- 

especie_mean_long_sepalo_petalo = []

for especie in filtro_por_especie:
    etiqueta_especie = dimensiones_clase_especie[dimensiones_clase_especie[:, 4] == especie]
    mean_long_sepalo_petalo = np.mean(etiqueta_especie, axis=0)
    especie_mean_long_sepalo_petalo.append(mean_long_sepalo_petalo)

arr_especie_mean_long_sepalo_petalo = np.array(especie_mean_long_sepalo_petalo)

x = arr_especie_mean_long_sepalo_petalo[0, 0] - arr_especie_mean_long_sepalo_petalo[0, 2]
y = arr_especie_mean_long_sepalo_petalo[1, 0] - arr_especie_mean_long_sepalo_petalo[1, 2]
z = arr_especie_mean_long_sepalo_petalo[2, 0] - arr_especie_mean_long_sepalo_petalo[2, 2]

if x > y and z:
    print('La especie con la diferencia más grande entre la longitud mediana de los sépalos y los pétalos es:', nombres_clase_especie[0])
elif y > x and z:
    print('La especie con la diferencia más grande entre la longitud mediana de los sépalos y los pétalos es:', nombres_clase_especie[1])
else:
    print('La especie con la diferencia más grande entre la longitud mediana de los sépalos y los pétalos es:', nombres_clase_especie[2])